GET http://localhost:3000/movies

###
GET http://localhost:3000/movies/5fcc642060496b5da2acfbea

###

DELETE http://localhost:3000/movies/5fcc736a7b090862b49af68b

###

PATCH http://localhost:3000/movies/5fcc642060496b5da2acfbea
Content-Type: application/json


###

POST http://localhost:3000/movies
Content-Type: application/json
